#!/bin/sh
PATH=/bin:/sbin:/usr/bin:/usr/sbin
echo started

mount -t proc     proc     /proc
mount -t sysfs    sysfs    /sys
mount -t devtmpfs none     /dev
mount -t tmpfs    tmpfs    /run
mount -t tmpfs    tmpfs    /tmp        # libudev-zero's UDEV_MONITOR_DIR lives here

echo "mounted!"
echo 0 > /proc/sys/kernel/printk
clear

mdev -s              # populate /dev and do an initial coldplug scan
mdev -d &            # daemonize mdev's hotplug listener (busybox mdev -d, or use
                      # a mdev.conf hotplug rule that calls libudev-zero's rebroadcast
                      # helper so new uevents land in /tmp/.libudev-zero)

while true; do
    pb-discover &
    petitboot-nc
    kill %1 2>/dev/null
    sleep 1
done
