# SPDX-License-Identifier: ISC

option(
    'symbol-versioning',
    type: 'feature',
    value: 'auto',
    description: 'Version exported symbols for compatibility with the libudev ABI',
)

option(
    'usb-ids-path',
    type: 'string',
    value: '',
    description: 'Path to the usb.ids database (default: <prefix>/<datadir>/hwdata/usb.ids)',
)
